# Model parameters
model: yolov8n.pt  # yolov8n/s/m/l/x
pretrained: True

# Training parameters
epochs: 100
batch: 16
imgsz: 640
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0

# Dataset configuration
data: data/coco.yaml

# Augmentation
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0